Website/BookStore/BookStore.Website/Areas/Admin/Models/TagViewModel.cs
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Utils.Global;
using BookStore.Website.Models;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BookStore.Website.Areas.Admin.Models
{
    public class TagViewModel : BaseViewModel
    {
        public int TagId { get; set; }
        public int? ParentId { get; set; }
        public int? InfoId { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên tag")]
        [Display(Name = "Tên tag")]
        public string TagName { get; set; }
        
        [Display(Name = "Từ khóa")]
        public string? Keyword { get; set; }

        [Display(Name = "Mô tả")]
        public string? Decription { get; set; }

        [Display(Name = "Liên kết")]
        public string? Slug { get; set; }
        public string? ReturnUrl { get; set; }

        public CreateTagRequest ToCreateCommand()
        {
            return new CreateTagRequest
            {
                TagName = TagName,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(TagName),
                Status = Common.Shared.Model.Status.Active,
                ParentId = null,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public UpdateTagRequest ToUpdateCommand()
        {
            return new UpdateTagRequest
            {
                TagName = TagName,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(TagName),
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Controllers/TagController.cs
using AutoMapper;
using BookStore.Common.Shared.Model;
using BookStore.DAL;
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Logic.Queries.Interface;
using BookStore.Utils.Extension;
using BookStore.Utils.Global;
using BookStore.Website.Areas.Admin.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Internal;
using Newtonsoft.Json;
using System.Data;
using System.Security.Claims;

namespace BookStore.Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class TagController : Controller
    {
        public const string TAGS = "tags";
        private readonly ITagQueries tagQueries;
        private readonly IMapper mapper;
        private readonly IMediator mediator;
        private readonly AppDatabase database;

        public TagController(ITagQueries tagQueries,
            IMapper mapper,
            IMediator mediator,
            AppDatabase database)
        {
            this.tagQueries = tagQueries;
            this.mapper = mapper;
            this.mediator = mediator;
            this.database = database;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreateTagToBook(string returnUrl, int InfoId)
        {
            TagViewModel model = new TagViewModel();
            model.InfoId = InfoId;
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var tagSave = new Tag();
                var tag = tagQueries.GetTagByName(model.TagName);
                if(tag == null)
                {
                    var tagResult = new BaseCommandResultWithData<Tag>();
                    tagResult = await mediator.Send(model.ToCreateCommand());
                    tagSave = tagResult.Data;
                }
                tagSave = tag;
                if (model.InfoId != 0)
                {
                    var info = database.Infos
                         .Where(i => i.Status != Status.Delete)
                         .FirstOrDefault(i => i.InfoId == model.InfoId);
                    if (info != null)
                    {
                        var tagInfoResult = new BaseCommandResultWithData<TagInfo>();
                        tagInfoResult = await mediator.Send(new AddTagAndInfoToTagInfoRequest
                        {
                            Tag = tagSave,
                            Info = info
                        });
                    }
                }
            }
            database.SaveChanges();
            return LocalRedirect(model.ReturnUrl);
        }

        public IActionResult AddTagToSession(string returnUrl)
        {
            TagViewModel model = new TagViewModel();
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddTagToSession(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                var session = HttpContext.Session;
                List<TagViewModel> list = new List<TagViewModel>();

                string? tagGet = session.GetString(TAGS);
                if (tagGet != null)
                {
                    List<TagViewModel>? listGet = JsonConvert.DeserializeObject<List<TagViewModel>>(tagGet);
                    if (listGet != null)
                    {
                        list = listGet;
                    }
                }
                string? decodedHtml = System.Net.WebUtility.HtmlDecode(model.Decription);
                model.Decription = decodedHtml;
                list.Add(model);
                string tags = JsonConvert.SerializeObject(list);
                session.SetString(TAGS, tags);
            }
            return LocalRedirect(model.ReturnUrl ?? "/Admin");
        }

        [HttpGet]
        public async Task<IActionResult> DeleteTagFromBookAsync(string returnUrl, int id, int TagId, int InfoId)
        {
            var session = HttpContext.Session;
            string? tagGet = session.GetString(TAGS);
            if (tagGet != null)
            {
                List<TagViewModel>? list = JsonConvert.DeserializeObject<List<TagViewModel>>(tagGet);
                if (list != null)
                {
                    var tag = tagQueries.GetDetail(TagId);
                    if (tag == null)
                    {
                        list.RemoveAt(id);
                        string tags = JsonConvert.SerializeObject(list);
                        session.SetString(TAGS, tags);
                    }
                    else
                    {
                        var command = new DeleteTagInfoRequest()
                        {
                            TagId = TagId,
                            InfoId = InfoId,
                            RequestId = HttpContext.Connection?.Id,
                            IpAddress = HttpContext.Connection?.RemoteIpAddress?.ToString(),
                            UserName = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value
                        };
                        var result = await mediator.Send(command);
                    }
                }
            }
            return LocalRedirect(returnUrl ?? "/Admin");
        }

        [HttpGet]
        public IActionResult UpdateTagToBook(string returnUrl, int id)
        {
            TagViewModel model = new TagViewModel();
            var session = HttpContext.Session;
            string? tagGet = session.GetString(TAGS);
            if (tagGet != null)
            {
                List<TagViewModel>? list = JsonConvert.DeserializeObject<List<TagViewModel>>(tagGet);
                if (list != null)
                {
                    var tag = mapper.Map<TagViewModel>(tagQueries.GetDetail(id));
                    if (tag == null)
                    {
                        model = list[id];
                        model.ReturnUrl = returnUrl;
                    }
                    else 
                    {
                        model = tag;
                        model.ReturnUrl = returnUrl;
                    }
                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAsync(TagViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.SetFromContext(HttpContext);
                var commandResult = new BaseCommandResultWithData<Tag>();
                var updateCommand = model.ToUpdateCommand();
                commandResult = await mediator.Send(updateCommand);
            }
            return Redirect(model.ReturnUrl);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(TagViewModel model)
        {
            return View();
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Tag/AddTagToSession.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model TagViewModel

@{
    ViewData["Title"] = "AddTagToSession";
    Layout = null;
}
<script src="~/ckeditor/ckeditor.js"></script>
<form autocomplete="off" id="form-tag-dialog" method="post" asp-action="AddTagToSession" asp-controller="Tag" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl"/>
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input required autocomplete="off" type="text" asp-for="TagName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="TagName"></label>
                <div class="row">
                    <span asp-validation-for="TagName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input type="text" autocomplete="off" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field">
                <label asp-for="Decription"></label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="back" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
<script>
    CKEDITOR.replace("Decription", {
        language: "vi"
    });
</script>
<script src="~/js/admin/admin-my-script.js" type="text/javascript"></script>
@section scripts
{
    <partial name="_ValidationScriptsPartial" />
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Tag/CreateTagToBook.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model TagViewModel

@{
    ViewData["Title"] = "CreateTagToBook";
    Layout = null;
}

<script src="~/ckeditor/ckeditor.js"></script>
<form autocomplete="off" id="form-tag-dialog" method="post" asp-action="Create" asp-controller="Tag" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <input type="hidden" asp-for="InfoId" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input required autocomplete="off" type="text" asp-for="TagName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="TagName"></label>
                <div class="row">
                    <span asp-validation-for="TagName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input type="text" autocomplete="off" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field">
                <label asp-for="Decription"></label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="back" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
<script>
    CKEDITOR.replace("Decription", {
        language: "vi"
    });
</script>
<script src="~/js/admin/admin-my-script.js" type="text/javascript"></script>
@section scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Tag/UpdateTagToSession.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model TagViewModel


@{
    ViewData["Title"] = "UpdateTagToSession";
    Layout = null;
}

<script src="~/ckeditor/ckeditor.js"></script>
<form autocomplete="off" id="form-tag-dialog" method="post" asp-action="UpdateTagToSession" asp-controller="Tag" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <input type="hidden" asp-for="TagId" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input required autocomplete="off" type="text" asp-for="TagName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="TagName"></label>
                <div class="row">
                    <span asp-validation-for="TagName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input type="text" autocomplete="off" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field">
                <label asp-for="Decription"></label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="back" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
<script>
    CKEDITOR.replace("Decription", {
        language: "vi"
    });
</script>
@section scripts
    {
    <partial name="_ValidationScriptsPartial" />
}