Website/BookStore/BookStore.Website/Areas/Admin/Models/BookViewModel.cs
using AutoMapper;
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Logic.Shared.Model;
using BookStore.Utils.Global;
using BookStore.Website.Models;
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BookStore.Website.Areas.Admin.Models
{
    [BindProperties]
    public class BookViewModel : BaseViewModel
    {
        //[RegularExpression(@"/^[0-9a-zA-Z_ÀÁÂÃÈÉÊẾÌÍÒÓÔÕÙÚĂĐĨŨƠàáâãèéêếìíòóôõùúăđĩũơƯĂẠẢẤẦẨẪẬẮẰẲẴẶẸẺẼỀỀỂưăạảấầẩẫậắằẳẵặẹẻẽềềểỄỆỈỊỌỎỐỒỔỖỘỚỜỞỠỢỤỦỨỪễệỉịọỏốồổỗộớờởỡợụủứừỬỮỰỲỴÝỶỸửữựỳỵỷỹ\ ]+$/", ErrorMessage = "Bạn phải nhập ký tự và số")]

        //Database Model
        public int BookId { get; set; }
        public int InfoId { get; set; }
        public int CategoryId { get; set; } = 0;

        [Required(ErrorMessage = "Bạn phải nhập tiêu đề của sách")]
        [StringLength(70, MinimumLength = 3, ErrorMessage = "Bạn phải nhập từ {1} đến {0}")]
        [Display(Name = "Tiêu đề")]
        public string Title { get; set; }

        [StringLength(60, ErrorMessage = "Bạn phải nhập được đến {0}")]
        [Display(Name = "Từ khóa")]
        public string? Keyword { get; set; }

        [Display(Name = "Mô tả")]
        public string? Decription { get; set; }

        [Display(Name = "Liên kết")]
        public string? Slug { get; set; }

        //ViewModel dùng để hiển thị và trích xuất dữ liệu
        public SeriesViewModel SeriesViewModel { get; set; }
        public InfoViewModel InfoViewModel { get; set; }
        public EditionViewModel EditionViewModel { get; set; }
        public List<CategorySummaryModel>? Categories { get; set; }

        public CreateBookRequest ToCreateCommand()
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(Info info)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                Info = info,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(Edition edition)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                Edition = edition,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
        public CreateBookRequest ToCreateCommand(List<BookImage> bookImages)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                BookImages = bookImages,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(Info info, Edition edition)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                Info = info,
                Edition = edition,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(List<BookImage> bookImages, Edition edition)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                BookImages = bookImages,
                Edition = edition,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(List<BookImage> bookImages, Info info)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                BookImages = bookImages,
                Info = info,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public CreateBookRequest ToCreateCommand(Info info, Edition edition, List<BookImage> bookImages)
        {
            return new CreateBookRequest
            {
                CategoryId = CategoryId,
                InfoId = info.InfoId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                Info = info,
                Edition = edition,
                BookImages = bookImages,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public UpdateBookRequest ToUpdateCommand()
        {
            return new UpdateBookRequest
            {
                BookId = BookId,
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
        public UpdateBookRequest ToUpdateCommand(int InfoId, int CategoryId)
        {
            return new UpdateBookRequest
            {
                BookId = BookId,
                CategoryId = CategoryId,
                Title = Title,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(Title),
                Status = Common.Shared.Model.Status.Active,
                InfoId = InfoId,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Controllers/BookController.cs
using AutoMapper;
using BookStore.Common.Shared.Model;
using BookStore.DAL;
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Logic.Queries.Implement;
using BookStore.Logic.Queries.Interface;
using BookStore.Logic.Shared.Catalog.Interface;
using BookStore.Logic.Shared.Model;
using BookStore.Utils.Extension;
using BookStore.Utils.Global;
using BookStore.Website.Areas.Admin.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Newtonsoft.Json;
using System.Data;
using System.Globalization;
using System.Security.Claims;

namespace BookStore.Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BookController : Controller
    {
        private readonly IBookQueries bookQueries;
        private readonly ITagQueries tagQueries;
        private readonly ICategoryQueries categoryQueries;
        private readonly IPublisherQueries publisherQueries;
        private readonly IAuthorQueries authorQueries;
        private readonly IBookImageQueries bookImageQueries;
        private readonly IMediator mediator;
        private readonly IMapper mapper;
        private readonly AppDatabase database;
        public const string BOOKIMAGES = "bookimages";
        public const string PUBLISHERS = "publishers";
        public const string TAGS = "tags";
        public const string AUTHORS = "authors";

        public BookController(IBookQueries bookQueries,
            ITagQueries tagQueries,
            ICategoryQueries categoryQueries,
            IPublisherQueries publisherQueries,
            IAuthorQueries authorQueries,
            IBookImageQueries bookImageQueries,
            IMediator mediator,
            IMapper mapper,
            AppDatabase database)
        {
            this.bookQueries = bookQueries;
            this.tagQueries = tagQueries;
            this.categoryQueries = categoryQueries;
            this.publisherQueries = publisherQueries;
            this.authorQueries = authorQueries;
            this.bookImageQueries = bookImageQueries;
            this.mediator = mediator;
            this.mapper = mapper;
            this.database = database;
        }
        public IActionResult Index()
        {
            var model = new List<BookSummaryModel>();
            model = bookQueries.GetAll();
            return View(model);
        }
        public IActionResult List()
        {
            var model = new List<BookSummaryModel>();
            model = bookQueries.GetAll();
            return PartialView(model);
        }

        [HttpGet]
        public async Task<IActionResult> StatusAsync(int id)
        {
            var command = new ChangeBookStatusRequest()
            {
                Id = id,
                RequestId = HttpContext.Connection?.Id,
                IpAddress = HttpContext.Connection?.RemoteIpAddress?.ToString(),
                UserName = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value
            };
            var result = await mediator.Send(command);
            return Json(new { success = result.Success, message = result.Message });
        }

        public IActionResult Trash()
        {
            var model = new List<BookSummaryModel>();
            model = bookQueries.GetAllDelete();
            return View(model);
        }

        public IActionResult ListTrash()
        {
            var model = new List<BookSummaryModel>();
            model = bookQueries.GetAllDelete();
            return PartialView(model);
        }

        [HttpGet]
        public async Task<IActionResult> ReTrash(int id)
        {
            var command = new RecoveryBookRequest()
            {
                Id = id,
                RequestId = HttpContext.Connection?.Id,
                IpAddress = HttpContext.Connection?.RemoteIpAddress?.ToString(),
                UserName = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value
            };
            var result = await mediator.Send(command);
            return Json(new { success = result.Success, message = result.Message });
        }

        [HttpGet]
        public IActionResult Create()
        {
            BookViewModel model = new BookViewModel();
            if (categoryQueries.GetAll().Count > 0)
            {
                model.Categories = categoryQueries.GetAll();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] BookViewModel model)
        {
            List<TagViewModel> tagsView = new List<TagViewModel>();
            List<PublisherViewModel> publishersView = new List<PublisherViewModel>();
            List<AuthorViewModel> authorsView = new List<AuthorViewModel>();
            List<BookImageViewModel> bookImagesView = new List<BookImageViewModel>();

            var session = HttpContext.Session;
            string? bookImages = session.GetString(BOOKIMAGES);
            if (bookImages != null)
            {
                bookImagesView = JsonConvert.DeserializeObject<List<BookImageViewModel>>(bookImages);
            }
            string? publishers = session.GetString(PUBLISHERS);
            if (publishers != null)
            {
                publishersView = JsonConvert.DeserializeObject<List<PublisherViewModel>>(publishers);
            }
            string? authors = session.GetString(AUTHORS);
            if (authors != null)
            {
                authorsView = JsonConvert.DeserializeObject<List<AuthorViewModel>>(authors);
            }
            string? tags = session.GetString(TAGS);
            if (tags != null)
            {
                tagsView = JsonConvert.DeserializeObject<List<TagViewModel>>(tags);
            }

            if (ModelState.IsValid)
            {
                List<Tag> listTag = new List<Tag>();
                List<Publisher> listPublisher = new List<Publisher>();
                List<Author> listAuthor = new List<Author>();
                List<BookImage> listBookImage = new List<BookImage>();

                //Command result
                var bookResult = new BaseCommandResultWithData<Book>();
                //Có dùng list
                var authorResult = new BaseCommandResultWithData<Author>();
                var tagResult = new BaseCommandResultWithData<Tag>();
                var publisherResult = new BaseCommandResultWithData<Publisher>();
                var bookImageResult = new BaseCommandResultWithData<BookImage>();
                //Không dùng list
                var infoResult = new BaseCommandResultWithData<Info>();
                var editionResult = new BaseCommandResultWithData<Edition>();
                var seriesResult = new BaseCommandResultWithData<Series>();
                //Liên kết nhiều nhiều
                var authorBookResult = new BaseCommandResultWithData<AuthorBook>();
                var editionPublisherResult = new BaseCommandResultWithData<EditionPublisher>();
                var tagInfoResult = new BaseCommandResultWithData<TagInfo>();
                SetContextToModel(model, tagsView, publishersView, authorsView, bookImagesView);

                await CreateTagAndAddToListAsync(tagsView, listTag, tagResult);
                await CreateAuthorAndAddToListAsync(authorsView, listAuthor, authorResult);
                await CreatePublisherAndAddToListAsync(publishersView, listPublisher, publisherResult);
                await CreateBookImageAndAddToListAsync(bookImagesView, listBookImage, bookImageResult);

                seriesResult = await mediator.Send(model.SeriesViewModel.ToCreateCommand());
                if (seriesResult.Success)
                {
                    infoResult = await mediator.Send(model.InfoViewModel.ToCreateCommand(seriesResult.Data));
                }
                var edition = bookQueries.GetBookByISBN(model.EditionViewModel.ISBN);
                if (edition != null)
                {
                    model.EditionViewModel.ISBN = " ";
                    return View(model);
                }
                editionResult = await mediator.Send(model.EditionViewModel.ToCreateCommand());
                if (editionResult.Success && infoResult.Success && listBookImage.Count > 0)
                {
                    string? decodedHtml = System.Net.WebUtility.HtmlDecode(model.Decription);
                    model.Decription = decodedHtml;
                    bookResult = await mediator.Send(model.ToCreateCommand(infoResult.Data, editionResult.Data, listBookImage));
                }

                if(infoResult.Success && listTag.Count > 0)
                {
                    foreach (var item in listTag)
                    {
                        tagInfoResult = await mediator.Send(new AddTagAndInfoToTagInfoRequest
                        {
                            Tag = item,
                            Info = infoResult.Data
                        });
                    }
                }

                if(bookResult.Success && listAuthor.Count > 0)
                {
                    foreach (var item in listAuthor)
                    {
                        authorBookResult = await mediator.Send(new AddAuthorAndBookToAuthorBookRequest
                        {
                            Author = item,
                            Book = bookResult.Data
                        });
                    }
                }

                if (editionResult.Success && listPublisher.Count > 0)
                {
                    foreach (var item in listPublisher)
                    {
                        editionPublisherResult = await mediator.Send(new AddEditionAndPublisherToEditionPubliserRequest

Website/BookStore/BookStore.Website/Areas/Admin/Views/Book/Index.cshtml
@using BookStore.DAL.Entities
@using BookStore.Logic.Shared.Model
@using BookStore.Common.Shared.Model
@model IEnumerable<BookSummaryModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Thư mục sách</strong>
            </div>
            <div class="col-md-6 text-end">
                <a asp-action="Create" asp-controller="Book" asp-area="Admin" class="btn btn-sm btn-success">
                    <i class="fa-solid fa-plus"></i> Thêm
                </a>
                <a asp-action="Trash" asp-controller="Book" asp-area="Admin" class="btn btn-sm btn-danger">
                    <i class="fa-solid fa-trash-alt"></i> Thùng rác
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th class="text-center">Tựa sách</th>
                    <th class="text-center">Tên tác giả</th>
                    <th class="text-center">Tập</th>
                    <th class="text-center">Mã sách</th>
                    <th class="text-center">Nhà xuất bản</th>
                    <th class="text-center">Trạng thái</th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="body-list">
                @Html.Partial("~/Areas/Admin/Views/Book/List.cshtml", Model)
            </tbody>
            <tfoot>
                <tr>
                    <th>Tựa sách</th>
                    <th>Tên tác giả</th>
                    <th>Đầu sách(tập)</th>
                    <th>Mã sách</th>
                    <th>Nhà xuất bản</th>
                    <th>Trạng thái</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>

Website/BookStore/BookStore.Website/Areas/Admin/Views/Book/List.cshtml
@using BookStore.DAL.Entities
@using BookStore.Logic.Shared.Model
@using BookStore.Common.Shared.Model
@model IEnumerable<BookSummaryModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@if (Model != null)
{
    @foreach (var book in Model)
    {
        <tr>
            <td>@book.Title</td>
            <td>
                @{
                    string? resultAuthor = " ";
                }
                @foreach (var author in book.AuthorBooks)
                {
                    if (author != null)
                    {
                        resultAuthor += author.Author.FirstName.ToString() + " " + author.Author.LastName.ToString() + "<br />";
                    }
                }
                @Html.Raw(resultAuthor)
            </td>
            <td>@book.VolumeNumber</td>
            <td>@book.ISBN</td>
            <td>
                @{
                    string? resultPublisher = " ";
                }
                @foreach (var publisher in book.Pulisher)
                {
                    if (publisher != null)
                    {
                        resultPublisher += publisher.Publisher.PulishingHouse + Html.Raw("<br />");
                    }
                }
                @Html.Raw(resultPublisher)
            </td>
            <td>
                @if (@book.Status == Status.Active)
                {
                    <button class="btn btn-success" onclick="ChangeStatus('@Url.Action("Status", "Book", new {@id = book.BookId})', '@Url.Action("List", "Book")')">
                        <i class="fa-solid fa-toggle-on"></i>
                    </button>
                }
                else
                {
                    <button class="btn btn-danger" onclick="ChangeStatus('@Url.Action("Status", "Book", new {@id = book.BookId})', '@Url.Action("List", "Book")')">
                        <i class="fa-solid fa-toggle-off"></i>
                    </button>
                }
            </td>
            <td>
                <a class="btn btn-success" asp-action="Update" asp-controller="Book" asp-route-id="@book.BookId">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                <button class="btn btn-danger" onclick="OnDelete('@Url.Action("Delete", "Book", new{@id = book.BookId})', '@Url.Action("List", "Book")')">
                    <i class="fa-solid fa-trash-can"></i>
                </button>
            </td>
        </tr>
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Book/ListTrash.cshtml
@using BookStore.DAL.Entities
@using BookStore.Logic.Shared.Model
@using BookStore.Common.Shared.Model
@model IEnumerable<BookSummaryModel>

@if (Model != null)
{
    @foreach (var book in Model)
    {
        <tr>
            <td>@book.Title</td>
            <td>
                @{
                    string? resultAuthor = " ";
                }
                @foreach (var author in book.AuthorBooks)
                {
                    if (author != null)
                    {
                        resultAuthor += author.Author.LastName.ToString() + " " + author.Author.FirstName.ToString() + Html.Raw("<br />");
                    }
                }
                @Html.Raw(resultAuthor)
            </td>
            <td>@book.VolumeNumber</td>
            <td>@book.ISBN</td>
            <td>
                @{
                    string? resultPublisher = " ";
                }
                @foreach (var publisher in book.Pulisher)
                {
                    if (publisher != null)
                    {
                        resultPublisher += publisher.Publisher.PulishingHouse + Html.Raw("<br />");
                    }
                }
                @Html.Raw(resultPublisher)
            </td>
            <td>
                <button class="btn btn-danger" onclick="Recovery('@Url.Action("ReTrash", "Book", new {@id = book.BookId})', '@Url.Action("ListTrash", "Book")')">
                    <i class="fa-solid fa-arrow-rotate-left"></i>
                </button>
            </td>
            <td>
                <a class="btn btn-success" asp-action="Detail" asp-controller="Book" asp-route-id="@book.BookId">
                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                </a>
                <button class="btn btn-danger" onclick="OnRemove('@Url.Action("Remove", "Book", new{@id = book.BookId})', '@Url.Action("ListTrash", "Book")')">
                    <i class="fa-solid fa-eraser"></i>
                </button>
            </td>
        </tr>
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Book/Trash.cshtml
@using BookStore.DAL.Entities
@using BookStore.Logic.Shared.Model
@using BookStore.Common.Shared.Model
@model IEnumerable<BookSummaryModel>
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers

@{
    ViewData["Title"] = "Trash";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Trash</h1>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Thùng rác của sách</strong>
            </div>
            <div class="col-md-6 text-end">
                <a asp-action="Index" asp-controller="Book" asp-area="Admin" class="btn btn-sm btn-primary">
                    <i class="fa-solid fa-caret-left"></i> Quay lại
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th class="text-center">Tựa sách</th>
                    <th class="text-center">Tên tác giả</th>
                    <th class="text-center">Tập</th>
                    <th class="text-center">Mã sách</th>
                    <th class="text-center">Nhà xuất bản</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody id="body-list-trash">
                @Html.Partial("~/Areas/Admin/Views/Book/ListTrash.cshtml", Model)
            </tbody>
            <tfoot>
                <tr>
                    <th>Tựa sách</th>
                    <th>Tên tác giả</th>
                    <th>Đầu sách(tập)</th>
                    <th>Mã sách</th>
                    <th>Nhà xuất bản</th>
                    <th></th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>