Website/BookStore/BookStore.Website/Areas/Admin/Models/AuthorViewModel.cs
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Utils.Global;
using BookStore.Website.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BookStore.Website.Areas.Admin.Models
{
    public class AuthorViewModel : BaseViewModel
    {
        public int AuthorId { get; set; }
        public int? BookId { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập họ và tên lót")]
        [StringLength(25, MinimumLength = 3, ErrorMessage = "Bạn phải nhập từ {1} đến {0}")]
        [Display(Name = "Họ và tên lót")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập tên của tác giả")]
        [StringLength(25, MinimumLength = 3, ErrorMessage = "Bạn phải nhập từ {1} đến {0}")]
        [Display(Name = "Tên")]
        public string LastName { get; set; }

        [Display(Name = "Ngày sinh")]
        public DateTime DateOfBirth { get; set; }

        [StringLength(20, ErrorMessage = "Bạn phải nhập được đến {0}")]
        [Display(Name = "Nơi ở")]
        public string? CountryOfResidence { get; set; }

        [StringLength(60, ErrorMessage = "Bạn phải nhập được đến {0}")]
        [Display(Name = "Từ khóa")]
        public string? Keyword { get; set; }

        [Display(Name = "Mô tả")]
        public string? Decription { get; set; }
        public string? ReturnUrl { get; set; }

        public CreateAuthorRequest ToCreateCommand()
        {
            return new CreateAuthorRequest
            {
                FirstName = FirstName,
                LastName = LastName,
                CountryOfResidence = CountryOfResidence,
                DateOfBirth = DateOfBirth,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(FirstName + " " + LastName),
                Status = Common.Shared.Model.Status.Active,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public UpdateAuthorRequest ToUpdateCommand()
        {
            return new UpdateAuthorRequest
            {
                FirstName = FirstName,
                LastName = LastName,
                CountryOfResidence = CountryOfResidence,
                DateOfBirth = DateOfBirth,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(FirstName + " " + LastName),
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Controllers/AuthorController.cs
using AutoMapper;
using BookStore.Common.Shared.Model;
using BookStore.DAL;
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Logic.Queries.Implement;
using BookStore.Logic.Queries.Interface;
using BookStore.Logic.Shared.Model;
using BookStore.Utils.Global;
using BookStore.Website.Areas.Admin.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Security.Claims;

namespace BookStore.Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class AuthorController : Controller
    {
        private readonly IAuthorQueries authorQueries;
        private readonly IMediator mediator;
        private readonly IMapper mapper;
        private readonly AppDatabase database;
        public const string AUTHORS = "authors";

        public AuthorController(IAuthorQueries authorQueries,
            IMediator mediator,
            IMapper mapper,
            AppDatabase database)
        {
            this.authorQueries = authorQueries;
            this.mediator = mediator;
            this.mapper = mapper;
            this.database = database;
        }

        public IActionResult Index()
        {
            var model = new List<AuthorSummaryModel>();
            model = authorQueries.GetAll();
            return View(model);
        }

        [HttpGet]
        public IActionResult CreateAuthorToBook(string returnUrl, int BookId)
        {
            AuthorViewModel model = new AuthorViewModel();
            model.BookId = BookId;
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(AuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var authorSave = new Author();
                var author = authorQueries.GetAuthorByName(model.FirstName, model.LastName);
                if (author == null)
                {
                    var ạuthorResult = new BaseCommandResultWithData<Author>();
                    ạuthorResult = await mediator.Send(model.ToCreateCommand());
                    authorSave = ạuthorResult.Data;
                }
                else
                {
                    authorSave = author;
                }
                if (model.BookId != 0)
                {
                    var book = database.Books
                         .Where(i => i.Status != Status.Delete)
                         .FirstOrDefault(i => i.BookId == model.BookId);
                    if (book != null)
                    {
                        var authorBookResult = new BaseCommandResultWithData<AuthorBook>();
                        authorBookResult = await mediator.Send(new AddAuthorAndBookToAuthorBookRequest
                        {
                            Author = authorSave,
                            Book = book
                        });
                    }
                }
            }
            database.SaveChanges();
            return LocalRedirect(model.ReturnUrl);
        }

        [HttpGet]
        public IActionResult AddAuthorToSession(string returnUrl)
        {
            AuthorViewModel model = new AuthorViewModel();
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAuthorToSession(AuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                var session = HttpContext.Session;
                List<AuthorViewModel> list = new List<AuthorViewModel>();

                string? authorGet = session.GetString(AUTHORS);
                if (authorGet != null)
                {
                    List<AuthorViewModel>? listGet = JsonConvert.DeserializeObject<List<AuthorViewModel>>(authorGet);
                    if (listGet != null)
                    {
                        list = listGet;
                    }
                }
                string? decodedHtml = System.Net.WebUtility.HtmlDecode(model.Decription);
                model.Decription = decodedHtml;
                list.Add(model);
                string authors = JsonConvert.SerializeObject(list);
                session.SetString(AUTHORS, authors);
            }
            return LocalRedirect(model.ReturnUrl);
        }

        public async Task<IActionResult> DeleteAuthorFromBookAsync(string returnUrl, int id, int AuthorId, int BookId)
        {
            var session = HttpContext.Session;
            string? authorGet = session.GetString(AUTHORS);
            if (authorGet != null)
            {
                List<AuthorViewModel>? list = JsonConvert.DeserializeObject<List<AuthorViewModel>>(authorGet);
                if (list != null)
                {
                    var author = authorQueries.GetDetail(AuthorId);
                    if (author == null)
                    {
                        list.RemoveAt(id);
                        string authors = JsonConvert.SerializeObject(list);
                        session.SetString(AUTHORS, authors);
                    }
                    else
                    {
                        var command = new DeleteAuthorBookRequest()
                        {
                            AuthorId = AuthorId,
                            BookId = BookId,
                            RequestId = HttpContext.Connection?.Id,
                            IpAddress = HttpContext.Connection?.RemoteIpAddress?.ToString(),
                            UserName = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value
                        };
                        var result = await mediator.Send(command);
                    }
                }
            }
            return LocalRedirect(returnUrl ?? "/");
        }

        [HttpGet]
        public IActionResult Update(string returnUrl, int id)
        {
            AuthorViewModel model = new AuthorViewModel();
            var session = HttpContext.Session;
            string? tagGet = session.GetString(AUTHORS);
            if (tagGet != null)
            {
                List<AuthorViewModel>? list = JsonConvert.DeserializeObject<List<AuthorViewModel>>(tagGet);
                if (list != null)
                {
                    var author = mapper.Map<AuthorViewModel>(authorQueries.GetDetail(id));
                    if (author == null)
                    {
                        model = list[id];
                        model.ReturnUrl = returnUrl;
                    }
                    else
                    {
                        model = author;
                        model.ReturnUrl = returnUrl;
                    }
                }
            }
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateAsync(AuthorViewModel model)
        {
            if (ModelState.IsValid)
            {
                model.SetFromContext(HttpContext);
                var commandResult = new BaseCommandResultWithData<Author>();
                var updateCommand = model.ToUpdateCommand();
                commandResult = await mediator.Send(updateCommand);
            }
            return Redirect(model.ReturnUrl);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            return View();
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Author/AddAuthorToSession.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model AuthorViewModel
@{
    ViewData["Title"] = "AddAuthorToSession";
    Layout = null;
}
<script src="~/ckeditor/ckeditor.js"></script>
<form method="post" id="form-dialog" autocomplete="off" asp-action="AddAuthorToSession" asp-controller="Author" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" maxlength="25" required type="text" asp-for="FirstName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="FirstName"></label>
                <div class="row">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" maxlength="25" required type="text" asp-for="LastName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="LastName"></label>
                <div class="row">
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" data-date-format="dd/MM/yyyy" type="date" asp-for="DateOfBirth" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="DateOfBirth"></label>
                <div class="row">
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input autocomplete="off" type="text" asp-for="CountryOfResidence" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="CountryOfResidence"></label>
                <div class="row">
                    <span asp-validation-for="CountryOfResidence" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input autocomplete="off" maxlenght="60" type="text" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field">
                <label for="Decription">Mô tả</label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="@Model.Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
                <div class="row">
                    <span asp-validation-for="Decription" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="back" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
@section scripts
{

    <partial name="_ValidationScriptsPartial" />
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Author/CreateAuthorToBook.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model AuthorViewModel

@{
    ViewData["Title"] = "CreateAuthorToBook";
    Layout = null;
}

<script src="~/ckeditor/ckeditor.js"></script>
<form method="post" id="form-dialog" autocomplete="off" asp-action="Create" asp-controller="Author" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <input type="hidden" asp-for="BookId" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" maxlength="25" required type="text" asp-for="FirstName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="FirstName"></label>
                <div class="row">
                    <span asp-validation-for="FirstName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" maxlength="25" required type="text" asp-for="LastName" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="LastName"></label>
                <div class="row">
                    <span asp-validation-for="LastName" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" data-date-format="dd/MM/yyyy" type="date" asp-for="DateOfBirth" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="DateOfBirth"></label>
                <div class="row">
                    <span asp-validation-for="DateOfBirth" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input autocomplete="off" maxlength="20" type="text" asp-for="CountryOfResidence" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="CountryOfResidence"></label>
                <div class="row">
                    <span asp-validation-for="CountryOfResidence" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-6 form-field p-2">
                <input autocomplete="off" maxlenght="60" type="text" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field">
                <label for="Decription">Mô tả</label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="@Model.Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
                <div class="row">
                    <span asp-validation-for="Decription" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="back" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
@section scripts
    {

    <partial name="_ValidationScriptsPartial" />
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Author/Index.cshtml
@using BookStore.DAL.Entities
@using BookStore.Logic.Shared.Model
@model IEnumerable<AuthorSummaryModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-md-6">
                <strong class="text-uppercase text-danger">Danh sách loại sản phẩm</strong>
            </div>
            <div class="col-md-6 text-end">
                <a href="@Url.Action("Create", "Author")" class="btn btn-sm btn-success">
                    <i class="fa-solid fa-plus"></i> Thêm
                </a>
                <a href="@Url.Action("Trash", "Author")" class="btn btn-sm btn-danger">
                    <i class="fa-solid fa-trash-alt"></i> Thùng rác
                </a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table id="datatablesSimple">
            <thead>
                <tr>
                    <th>Tên tác giả</th>
                    <th>Ngày sinh</th>
                    <th>Quốc tịch</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @if (Model != null)
                {
                    @foreach (var author in Model)
                    {
                        <tr>
                            <td>@author.AuthorName</td>
                            <td>@author.DateOfBirth</td>
                            <td>@author.CountryOfResidence</td>
                            <td>
                                <a class="btn btn-success d-inline" asp-action="Detail" asp-controller="Author" asp-route-id="@author.AuthorId">
                                    <i class="fa-solid fa-arrow-up-right-from-square"></i>
                                </a>
                                <a class="btn btn-success d-inline" asp-action="Delete" asp-controller="Author" asp-route-id="@author.AuthorId">
                                    <i class="fa-solid fa-trash-can"></i>
                                </a>
                            </td>
                        </tr>
                    }
                }
            </tbody>
            <tfoot>
                <tr>
                    <th>Tên tác giả</th>
                    <th>Ngày sinh</th>
                    <th>Quốc tịch</th>
                    <th></th>
                </tr>
            </tfoot>
        </table>
    </div>
</div>