Website/BookStore/BookStore.Website/Areas/Admin/Models/PublisherViewModel.cs
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Utils.Global;
using BookStore.Website.Models;
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace BookStore.Website.Areas.Admin.Models
{
    public class PublisherViewModel : BaseViewModel
    {
        public int PublisherId { get; set; }
        public int EditionId { get; set; }

        [Required(ErrorMessage = "Bạn phải nhập nhà xuất bản")]
        [Display(Name = "Nhà xuất bản")]
        public string PulishingHouse { get; set; }

        [Display(Name = "Quốc gia")]
        public string? Country { get; set; }

        [Display(Name = "Từ khóa")]
        public string? Keyword { get; set; }

        [Display(Name = "Mô tả")]
        public string? Decription { get; set; }

        [Display(Name = "Liên kết")]
        public string? Slug { get; set; }
        public string? ReturnUrl { get; set; }

        public CreatePublisherRequest ToCreateCommand()
        {
            return new CreatePublisherRequest
            {
                PulishingHouse = PulishingHouse,
                Country = Country,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(PulishingHouse),
                Status = Common.Shared.Model.Status.Active,
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }

        public UpdatePublisherRequest ToUpdateCommand()
        {
            return new UpdatePublisherRequest
            {
                PulishingHouse = PulishingHouse,
                Country = Country,
                Keyword = Keyword,
                Decription = Decription,
                Slug = AppGlobal.GenerateSlug(PulishingHouse),
                UserName = UserName,
                IpAddress = IpAddress,
                RequestId = RequestId
            };
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Controllers/PublisherController.cs
using AutoMapper;
using BookStore.Common.Shared.Model;
using BookStore.DAL;
using BookStore.DAL.Entities;
using BookStore.Logic.Command.Request;
using BookStore.Logic.Queries.Implement;
using BookStore.Logic.Queries.Interface;
using BookStore.Utils.Global;
using BookStore.Website.Areas.Admin.Models;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Data;
using System.Net;
using System.Security.Claims;

namespace BookStore.Website.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class PublisherController : Controller
    {
        public const string PUBLISHERS = "publishers";
        private readonly IPublisherQueries publisherQueries;
        private readonly IMediator mediator;
        private readonly AppDatabase database;

        public PublisherController(IPublisherQueries publisherQueries,
            IMediator mediator,
            AppDatabase database)
        {
            this.publisherQueries = publisherQueries;
            this.mediator = mediator;
            this.database = database;
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CreatePublisherToBook(string returnUrl, int EditionId)
        {
            PublisherViewModel model = new PublisherViewModel();
            model.EditionId = EditionId;
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(PublisherViewModel model)
        {
            if (ModelState.IsValid)
            {
                var publisherSave = new Publisher();
                var publisher = publisherQueries.GetPublisherByPulishingHouse(model.PulishingHouse);
                if (publisher == null)
                {
                    var publisherResult = new BaseCommandResultWithData<Publisher>();
                    publisherResult = await mediator.Send(model.ToCreateCommand());
                    publisherSave = publisherResult.Data;
                }
                publisherSave = publisher;
                if (model.EditionId != 0)
                {
                    var edition = database.Editions
                         .Where(e => e.Status != Status.Delete)
                         .FirstOrDefault(e => e.EditionId == model.EditionId);
                    if (edition != null)
                    {
                        var authorBookResult = new BaseCommandResultWithData<EditionPublisher>();
                        authorBookResult = await mediator.Send(new AddEditionAndPublisherToEditionPubliserRequest
                        {
                            Edition = edition,
                            Publisher = publisherSave
                        });
                    }
                }
            }
            database.SaveChanges();
            return LocalRedirect(model.ReturnUrl);
        }

        [HttpGet]
        public IActionResult AddPublisherToSession(string returnUrl)
        {
            PublisherViewModel model = new PublisherViewModel();
            model.ReturnUrl = returnUrl;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPublisherToSession([FromForm] PublisherViewModel model)
        {
            if (ModelState.IsValid)
            {
                var session = HttpContext.Session;
                List<PublisherViewModel> list = new List<PublisherViewModel>();

                string? publisherGet = session.GetString(PUBLISHERS);
                if (publisherGet != null)
                {
                    List<PublisherViewModel>? listGet = JsonConvert.DeserializeObject<List<PublisherViewModel>>(publisherGet);
                    if (listGet != null)
                    {
                        list = listGet;
                    }
                }
                string? decodedHtml = System.Net.WebUtility.HtmlDecode(model.Decription);
                model.Decription = decodedHtml;
                list.Add(model);
                string publishers = JsonConvert.SerializeObject(list);
                session.SetString(PUBLISHERS, publishers);
            }
            return LocalRedirect(model.ReturnUrl ?? "/Admin");
        }

        public async Task<IActionResult> DeletePublisherFromBookAsync(string returnUrl, int id, int PublisherId, int EditionId)
        {
            var session = HttpContext.Session;
            string? publisherGet = session.GetString(PUBLISHERS);
            if (publisherGet != null)
            {
                List<PublisherViewModel>? list = JsonConvert.DeserializeObject<List<PublisherViewModel>>(publisherGet);
                if (list != null)
                {
                    var publisher = publisherQueries.GetDetail(PublisherId);
                    if (publisher == null)
                    {
                        list.RemoveAt(id);
                        string publishers = JsonConvert.SerializeObject(list);
                        session.SetString(PUBLISHERS, publishers);
                    }
                    else
                    {
                        var command = new DeleteEditionPublisherRequest()
                        {
                            PublisherId = PublisherId,
                            EditionId = EditionId,
                            RequestId = HttpContext.Connection?.Id,
                            IpAddress = HttpContext.Connection?.RemoteIpAddress?.ToString(),
                            UserName = HttpContext.User?.Claims?.FirstOrDefault(x => x.Type == ClaimTypes.Name)?.Value
                        };
                        var result = await mediator.Send(command);
                    }
                }
            }
            return LocalRedirect(returnUrl ?? "/Admin");
        }

        [HttpGet]
        public IActionResult Update(int? id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Update(PublisherViewModel model)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult Delete(PublisherViewModel model)
        {
            return View();
        }
    }
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Publisher/AddPublisherToSession.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model PublisherViewModel
@{
    ViewData["Title"] = "AddPublisherToSession";
    Layout = null;
}
<script src="~/ckeditor/ckeditor.js"></script>
<form id="form-dialog" method="post" autocomplete="off" asp-action="AddPublisherToSession" asp-controller="Publisher" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="PulishingHouse" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="PulishingHouse"></label>
                <div class="row">
                    <span asp-validation-for="PulishingHouse" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="Country" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Country"></label>
                <div class="row">
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field p-2 mt-3">
                <label asp-for="Decription"></label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="save" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
<script>
    CKEDITOR.replace("Decription", {
        language: "vi"
    });
</script>
<script src="~/js/admin/admin-my-script.js" type="text/javascript"></script>
@section scripts
    {
    <partial name="_ValidationScriptsPartial" />
}

Website/BookStore/BookStore.Website/Areas/Admin/Views/Publisher/CreatePublisherToBook.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@using BookStore.Website.Areas.Admin.Models
@model PublisherViewModel
@{
    ViewData["Title"] = "CreatePublisherToBook";
    Layout = null;
}
<script src="~/ckeditor/ckeditor.js"></script>
<form id="form-dialog" method="post" autocomplete="off" asp-action="Create" asp-controller="Publisher" enctype="multipart/form-data" asp-area="Admin">
    <input type="hidden" asp-for="ReturnUrl" />
    <input type="hidden" asp-for="EditionId" />
    <div class="container">
        <div class="row mt-3">
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="PulishingHouse" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="PulishingHouse"></label>
                <div class="row">
                    <span asp-validation-for="PulishingHouse" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="Country" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Country"></label>
                <div class="row">
                    <span asp-validation-for="Country" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 col-lg-4 form-field p-2">
                <input autocomplete="off" type="text" asp-for="Keyword" class="form-control form-input" placeholder=" ">
                <label class="form-label" asp-for="Keyword"></label>
                <div class="row">
                    <span asp-validation-for="Keyword" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-12 form-field p-2 mt-3">
                <label asp-for="Decription"></label>
                <textarea autocomplete="off" type="text" id="Decription" name="Decription" asp-for="Decription" class="form-control form-input" placeholder=" "></textarea>
                <script>
                    // Replace all three <textarea> elements above with CKEditor instances.
                    CKEDITOR.replaceAll();
                </script>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-6 text-end">
            <button id="save" class="btn btn-primary" type="button" data-bs-dismiss="modal">
                <span class="fs-4">Back</span>  <i class="fa-solid fa-caret-left fs-4"></i>
            </button>
        </div>
        <div class="col-6">
            @*onclick="CreateBookImage('@Url.Action("Create", "BookImage")')"*@
            <button id="save" class="btn btn-success" type="submit">
                <span class="fs-4">Save</span> <i class="fa-solid fa-floppy-disk fs-4"></i>
            </button>
        </div>
    </div>
</form>
<script>
    CKEDITOR.replace("Decription", {
        language: "vi"
    });
</script>
<script src="~/js/admin/admin-my-script.js" type="text/javascript"></script>
@section scripts
    {
    <partial name="_ValidationScriptsPartial" />
}